version: "3.7"

services:
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - "./web:/app"
      - "/app/node_modules"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - "./api:/app"
      - "/app/node_modules"
    depends_on:
      - db
    ports:
      - 8001:8000
    stdin_open: true # https://github.com/docker/compose/issues/3896
  db:
    image: postgres:12.3-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data # persists db data locally
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cs2102_project
    ports:
      - 5432:5432
volumes:
  pg_data:
# https://mherman.org/blog/dockerizing-a-react-app/
