FROM node:14.8.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY web/package.json ./web/
COPY yarn.lock ./
RUN yarn install

# add app
COPY . ./

RUN yarn --cwd "web" build

# start app
CMD ["yarn", "start-prod"]
