version: "3.7"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
# https://mherman.org/blog/dockerizing-a-react-app/
